[project]
name    = "hello-world"
module  = "hello-world"
version = "1.0.0"
config  = "application.properties"

[scripts]
dev   = "go run ."
build = "go build -o bin/hello-world ."
test  = "go test ./..."
